package com.bagussubagja.flutter_liveness_detection_randomized_plugin.flutter_liveness_detection_randomized_plugin_example

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity()
